apiVersion: apps/v1
kind: Deployment
metadata:
  name: time-server
spec:
  selector:
    matchLabels:
      app: time-server
  template:
    metadata:
      labels:
        app: time-server
    spec:
      containers:
      - name: time-server
        image: ifilyaninitmo/time-server-mega-itmo:main
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8001
