on: push
name: Main
jobs:
  helm-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: helm-check
      uses: igabaydulin/helm-check-action@0.1.4
      with:
        chart_dir: helm-chart